### ISSUE TITLE
Number of Brackets Incorrectly Determined

### ISSUE THREAD

**Issue by polarizeme** [gregzaal/HDR-Merge#12]
Hiya!

First off, thanks so much for making this tool; it's gonna save me SO much time.

So I've come across an issue in the latest build (not sure if it's present in prev versions) where the metadata of the _first_ image from a bracketed set is NOT necessarily how your app figures out bracket sizes.

Example: For some reason the 7-bracket set of photos I got from my photographer has shots 4 and 5 in each bracket at the same exposure settings.

So say its:
01.tif - f/6.3
02.tif - f/5
03.tif - f/3.2
04.tif - f/2.8
05.tif - f/2.8
06.tif - f/4
07.tif - f/8
08.tif - f/6.3
09.tif - f/5
10.tif - f/3.2
11.tif - f/2.8
12.tif - f/2.8
13.tif - f/4
14.tif - f/8

And if I run this through your app, instead of identifying these as bracketed sets of 7 and determining that because 01.tif and 08.tif have the same exposure settings, it will get to 04.tif and 05.tif, see the same exposure settings, and determine these are brackets of 4 instead of brackets of 7. 

So it doesn't seem to match groups by the next sequential image to match the _first_ image's exposure settings, it just gets to the first match between _any_ two photo's exposure settings. Does that make sense?

I'm horrible at words, so if you need any additional info feel free to reach out =]

Cheers!

**Comment by gregzaal** [comment]
Hey, this should be manageable, can you provide a sample of files that I can test with?

**Comment by polarizeme** [comment]
@gregzaal Sure can! At least I hope I can haha. I did a bunch of manual shuffling to get them to process and I might not have the untouched files w/ the duplicate exposures anymore; I just got back home from a trip but I'll take a peek this week and get back to you as soon as I can.

Cheers!

**Comment by polarizeme** [comment]
@gregzaal didn't want to include too many photos due to size, so here are 3 sets of the 7-bracket photos as mentioned above.
https://drive.google.com/file/d/1T7fgS4vvsRLvXOTDFV1FQDIL5NDWFhd7/view?usp=sharing

Cheers and let me know if you need any other info.

**Comment by gregzaal** [comment]
Got them, thanks. I'll be off to the Blender conference next week so I'll only be able to look at this sometime next month.

**Comment by polarizeme** [comment]
No worries at all! I managed to manually get past this so there's no rush or anything =]
Enjoy the trip!

**Comment by gregzaal** [comment]
Sorry for only looking at this now. The issue comes from you having two images with identical exposure settings:

![2022-11-21_15-54-20](https://user-images.githubusercontent.com/5604661/203072775-bd323283-ed9c-4788-a0c2-0cb6044c350d.jpg)

Rather than looking for some pattern like consistent EV spacing or timestamps, this tool detects bracket sets by finding the next image in the sequence with the same exposure settings and assuming all the images between them are in the same set, and the duplicate is the start of the next set. I think. It's been a while since I wrote this :) This was meant to be a bit more flexible in cases where brackets were not necessarily consistently captured.

Point is, by deleting one of the duplicates, the merge should work. I'm guessing this is the workaround you discovered already.

**Comment by polarizeme** [comment]
Yup, you nailed it. No idea how on earth the stepping the camera captured 2 exposures at the exact same settings, but deleting the second was absolutely how I got around the issue haha.

Thanks for taking a peek =]

Cheers!
